### ISSUE TITLE
AttributeError: "'seqemb_mode_enabled'"

### ISSUE THREAD

**Issue by QUEST2179** [TencentAI4S/tfold#11]
The error seems from openfold-2.0.0, but how to fix it without downgrading openfold? Thanks!

python projects/tfold_ag/predict.py --pid_fpath=examples/prot_ids.nanoag.txt --fas_dpath=examples/fasta.files --msa_fpath=examples/msa.files/7sai_A.a3m --pdb_dpath=examples/pdb.files.nano
[09/28 07:01:04 root]: restoring the pre-trained tFold-PPI-SeqPT model ...
[09/28 07:01:08 root]: model weights restored from params/esm_ppi_650m.pth
[09/28 07:01:08 root]: restoring the pre-trained AlphaFold2 model ...
Traceback (most recent call last):
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 903, in __getitem__
    field = self._fields[key]
KeyError: 'seqemb_mode_enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 827, in __getattr__
    return self[attribute]
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 909, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'seqemb_mode_enabled'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 81, in <module>
    main()
  File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 73, in main
    predict(args.pid_fpath, args.fas_dpath,
  File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 62, in predict
    predictor = AgPredictor(
  File "/home/antibody/tfold-master/./tfold/deploy/ag_predictor.py", line 32, in __init__
    self.psp_featurizer = PspFeaturizer.restore(psp_path)
  File "/home/antibody/tfold-master/./tfold/deploy/psp_featurizer.py", line 51, in restore
    model = cls(config).eval()
  File "/home/antibody/tfold-master/./tfold/deploy/psp_featurizer.py", line 39, in __init__
    self.model = AlphaFold(self.config)
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/openfold-2.0.0-py3.9-linux-x86_64.egg/openfold/model/model.py", line 84, in __init__
    self.seqemb_mode = config.globals.seqemb_mode_enabled
  File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 829, in __getattr__
    raise AttributeError(e)
AttributeError: "'seqemb_mode_enabled'"

**Comment by Cloud-Rambler** [comment]
Hello, thank you for your attention to the work of tfold. You can download the latest code for running. The new version of the code has removed the dependency on the openfold package. Using the new code should not encounter the above problems.

**Comment by Wolkenwandler** [comment]
> The error seems from openfold-2.0.0, but how to fix it without downgrading openfold? Thanks!
> 
> python projects/tfold_ag/predict.py --pid_fpath=examples/prot_ids.nanoag.txt --fas_dpath=examples/fasta.files --msa_fpath=examples/msa.files/7sai_A.a3m --pdb_dpath=examples/pdb.files.nano [09/28 07:01:04 root]: restoring the pre-trained tFold-PPI-SeqPT model ... [09/28 07:01:08 root]: model weights restored from params/esm_ppi_650m.pth [09/28 07:01:08 root]: restoring the pre-trained AlphaFold2 model ... Traceback (most recent call last): File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 903, in **getitem** field = self._fields[key] KeyError: 'seqemb_mode_enabled'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 827, in **getattr** return self[attribute] File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 909, in **getitem** raise KeyError(self._generate_did_you_mean_message(key, str(e))) KeyError: "'seqemb_mode_enabled'"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 81, in main() File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 73, in main predict(args.pid_fpath, args.fas_dpath, File "/home/antibody/tfold-master/projects/tfold_ag/predict.py", line 62, in predict predictor = AgPredictor( File "/home/antibody/tfold-master/./tfold/deploy/ag_predictor.py", line 32, in **init** self.psp_featurizer = PspFeaturizer.restore(psp_path) File "/home/antibody/tfold-master/./tfold/deploy/psp_featurizer.py", line 51, in restore model = cls(config).eval() File "/home/antibody/tfold-master/./tfold/deploy/psp_featurizer.py", line 39, in **init** self.model = AlphaFold(self.config) File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/openfold-2.0.0-py3.9-linux-x86_64.egg/openfold/model/model.py", line 84, in **init** self.seqemb_mode = config.globals.seqemb_mode_enabled File "/home/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 829, in **getattr** raise AttributeError(e) AttributeError: "'seqemb_mode_enabled'"

Hello, thank you for your attention to the work of tfold. You can download the latest code for running. The new version of the code has removed the dependency on the openfold package. Using the new code should not encounter the above problems.
