### ISSUE TITLE
"seqmb_model_enabled" error on running example.

### ISSUE THREAD

**Issue by tsjain** [TencentAI4S/tfold#2]
I installed tFold and the sequence database as per the instructions, and downloaded the trained model weights.

On trying to run the following example:
python projects/tfold_ag/predict.py --pid_fpath=examples/prot_ids.abag.txt --fas_dpath=examples/fasta.files --msa_fpath=examples/msa.files/8df5_R.a3m --pdb_dpath=examples/pdb.files.abag

I get the following error:

`KeyError: 'seqemb_mode_enabled'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/tfold/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 827, in __getattr__
    return self[attribute]
  File "/home/ubuntu/miniforge3/envs/tfold/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 909, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'seqemb_mode_enabled'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "projects/tfold_ag/predict.py", line 81, in <module>
    main()
  File "projects/tfold_ag/predict.py", line 73, in main
    predict(args.pid_fpath, args.fas_dpath,
  File "projects/tfold_ag/predict.py", line 62, in predict
    predictor = AgPredictor(
  File "/home/ubuntu/tFold/tfold/deploy/ag_predictor.py", line 32, in __init__
    self.psp_featurizer = PspFeaturizer.restore(psp_path)
  File "/home/ubuntu/tFold/tfold/deploy/psp_featurizer.py", line 52, in restore
    model = cls(config).eval()
  File "/home/ubuntu/tFold/tfold/deploy/psp_featurizer.py", line 39, in __init__
    self.model = AlphaFold(self.config)
  File "/home/ubuntu/tFold/openfold/openfold/model/model.py", line 84, in __init__
    self.seqemb_mode = config.globals.seqemb_mode_enabled
  File "/home/ubuntu/miniforge3/envs/tfold/lib/python3.8/site-packages/ml_collections/config_dict/config_dict.py", line 829, in __getattr__
    raise AttributeError(e)
AttributeError: "'seqemb_mode_enabled'"`

**Comment by tsjain** [comment]
Issue was solved by installing openfold v1, instead of latest release

**Comment by Wolkenwandler** [comment]
Thanks for your attention, we have modified the installation in conda step to avoid such problems.
